export const FETCH_AUTHORS = 'FETCH_AUTHORS';
export const ADD_AUTHOR = 'ADD_AUTHOR';
export const DELETE_AUTHOR = 'DELETE_AUTHOR';
export const FETCH_AUTHOR = 'FETCH_AUTHOR';
export const FETCH_AUTHOR_LIST = 'FETCH_AUTHOR_LIST';
export const HANDLE_AUTHOR = 'HANDLE_AUTHOR';
